mod_name = "Dealing Heat"
mod_id = "dealing_heat"
mod_group = "org.teamvoided"
mod_version = "1.0.0"
mod_description = "Im glowing with posive energy (I will beat you up)"
github_repo = "Astratene/DealingHeat"
discord_invite = "https://discord.gg/KZ5Q364hEg"
authors = [ "TheHomopohbicCores" ]
license = "MIT"
version_range = ">=1.21.11 <26.1"
